language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
        - php: 7.0

mysql:
  database: elife_profile
  username: root
  encoding: utf8

cache:
  apt: true
  directories:
    - $HOME/.composer/cache
    - $HOME/.drush/cache
    - $HOME/.npm
    - $HOME/custom

addons:
  apt:
    packages:
      - apache2
      - libapache2-mod-fastcgi

before_install:
  - composer self-update

install:
  # Create MySQL Database
  - mysql -e 'create database elife_profile;'

  # Make node binary globally accessible.
  - node_bin=$(which node);sudo ln -s $node_bin /usr/local/bin

  # Set up Apache
  - sudo a2enmod rewrite actions fastcgi alias
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - if [[ -f ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ]] ; then sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf ; fi
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # configure apache virtual hosts
  - sudo cp -f tests/build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  # restart the server
  - sudo service apache2 restart
  - cat /etc/apache2/sites-available/default
  - sleep 5s

  # Install latest Drush 7.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --prefer-dist --no-interaction drush/drush:7.*

  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Set up site
  - ./setup.sh

  # Get Solr
  - if [[ ! -d "$HOME/custom/solr-5.2.1" ]]; then mkdir -p $HOME/custom; wget -qO- https://archive.apache.org/dist/lucene/solr/5.2.1/solr-5.2.1.tgz | tar xz --directory $HOME/custom; fi;
  - cp -r $HOME/custom/solr-5.2.1 $HOME # We don't want to cache the changes we make, so use a copy.
  - $HOME/solr-5.2.1/bin/solr start
  - mkdir -p $HOME/solr-5.2.1/server/solr/drupal
  - cp -r src/elife_profile/modules/contrib/search_api_solr/solr-conf/5.x $HOME/solr-5.2.1/server/solr/drupal
  - mv $HOME/solr-5.2.1/server/solr/drupal/5.x $HOME/solr-5.2.1/server/solr/drupal/conf
  - $HOME/solr-5.2.1/bin/solr create -c drupal -d $HOME/solr-5.2.1/server/solr/drupal

  # Install site
  - cp ./tests/build/travis.local.settings.php ./local.settings.php
  - ./install.sh

  # Setup display for selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Get Selenium
  - if [[ ! -e "$HOME/custom/selenium-server-standalone-2.44.0.jar" ]]; then wget --directory-prefix="$HOME/custom" http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar; fi;
  - java -jar $HOME/custom/selenium-server-standalone-2.44.0.jar -p 4444 > /dev/null 2>&1 &
  - sleep 5

script:
  - ./run-tests.sh
