language: php

php:
  - 5.5
  - 5.6
  - 7.0

matrix:
  allow_failures:
        - php: 7.0

mysql:
  database: elife_profile
  username: root
  encoding: utf8

before_install:
  - sudo apt-get update
  - composer self-update

install:
  # Create MySQL Database
  - mysql -e 'create database elife_profile;'

  # Make node binary globally accessible.
  - node_bin=$(which node);sudo ln -s $node_bin /usr/local/bin

  # Set up Apache
  - sudo apt-get install apache2 libapache2-mod-fastcgi
  - sudo a2enmod rewrite actions fastcgi alias
  - sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.conf
  - if [[ -f ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ]] ; then sudo cp ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf.default ~/.phpenv/versions/$(phpenv version-name)/etc/php-fpm.d/www.conf ; fi
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm

  # configure apache virtual hosts
  - sudo cp -f tests/build/travis-ci-apache /etc/apache2/sites-available/default
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/default
  # restart the server
  - sudo service apache2 restart
  - cat /etc/apache2/sites-available/default
  - sleep 5s

  # Install latest Drush 7.
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - composer global require --no-interaction drush/drush:7.*

  # Build Behat dependencies
  - cd ./tests/behat
  - composer install  --prefer-source --no-interaction
  - cd ../..

  # Disable sendmail
  - echo sendmail_path=`which true` >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini

  # Build site
  - cp ./tests/build/travis.local.settings.php ./local.settings.php
  - ./create.sh

  # Setup display for selenium
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 5

  # Get Selenium
  - wget http://selenium-release.storage.googleapis.com/2.44/selenium-server-standalone-2.44.0.jar
  - java -jar selenium-server-standalone-2.44.0.jar -p 4444 > /dev/null 2>&1 &
  - sleep 5

script:
  - ./run-tests.sh
